In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import seaborn as sns


sns.set()

In [3]:
data = pd.read_csv('Multiple+linear+regression.csv')
data.head()

    SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [4]:
data.describe()

               SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

## Create the multiple linear regression

### Declare the dependent and independent variables

In [6]:
y = data['GPA']
x = data[['SAT', 'Rand 1,2,3']]

## Regression itself

In [5]:
reg = LinearRegression()

In [7]:
reg.fit(x, y)

LinearRegression()

In [8]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [9]:
reg.intercept_

np.float64(0.29603261264909486)

## Calculating R-squared

In [11]:
reg.score(x,y) #the R-squared itself

0.4066811952814282

### Formula for Adjusted R^2
$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [12]:
x.shape #84 is the number of observations, 2 is the number of predictors

(84, 2)

In [14]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]

adjusted_r2 = 1 - (1-r2) * (n-1) / (n-p-1)
adjusted_r2

0.39203134825134

## Feature selection(F-regression)

It helps us to drop all unneeded features by:

In [15]:
from sklearn.feature_selection import f_regression

In [16]:
f_regression(x, y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [19]:
p_values = f_regression(x, y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [20]:
p_values.round(3)

array([0.   , 0.676])

### Creating a summary table

In [22]:
reg_summary = pd.DataFrame(data = x.columns.values, columns = ['Features'])
reg_summary

     Features
0         SAT
1  Rand 1,2,3

In [23]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [24]:
reg_summary

     Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

## Standardization

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
scaler = StandardScaler()

In [28]:
scaler.fit(x)

StandardScaler()

In [30]:
x_scaled = scaler.transform(x)

In [31]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984, -1.24637147],
       [-0.4934606 , -0.07002087],
       [-0.73406132, -1.24637147],
       [ 0.85390339, -1.24637147],
       [-0.67631715, -1.24637147],
       [ 0.09360513,  1.10632974],
       [ 0.33420585, -0.07002087],
       [ 0.03586096, -0.07002087],
       [-0.35872421,  1.10632974],
       [ 1.04638396,  1.10632974],
       [-0.65706909,  1.10632974],
       [-0.13737155, -0.07002087],
       [ 0.18984542,  1.10632974],
       [ 0.04548499, -1.24637147],
       [ 1.1618723 ,  1.10632974],
       [-1.37887123, -1.24637147],
       [ 1.39284898, -1.24637147],
       [ 0.76728713, -0.07002087],
       [-0.20473975, -0.07002087],
       [ 1.06563201, -1.24637147],
       [ 0.11285319, -1.24637147],
       [ 1.28698467,  1.10632974],
       [-0.41646838,  1.10632974],
       [ 0.09360513, -1.24637147],
       [ 0.59405462, -0.07002087],
       [-2.03330517, -0.07002087],
       [ 0.32458182, -1.24637147],
       [ 0.40157405, -1.24637147],
       [-1.10939843, -0.07002087],
       [ 1.03675993, -1.24637147],
       [-0.61857297, -0.07002087],
       [ 0.44007016, -0.07002087],
       [ 1.14262424, -1.24637147],
       [-0.35872421,  1.10632974],
       [ 0.45931822,  1.10632974],
       [ 1.88367444,  1.10632974],
       [ 0.45931822, -1.24637147],
       [-0.12774752, -0.07002087],
       [ 0.04548499,  1.10632974],
       [ 0.85390339, -0.07002087],
       [ 0.15134931, -0.07002087],
       [ 0.8250313 ,  1.10632974],
       [ 0.84427936,  1.10632974],
       [-0.64744506, -1.24637147],
       [ 1.24848856, -1.24637147],
       [ 0.85390339,  1.10632974],
       [ 1.69119387,  1.10632974],
       [ 1.6334497 ,  1.10632974],
       [ 1.46021718, -1.24637147],
       [ 1.68156984, -0.07002087],
       [-0.02188321,  1.10632974],
       [ 0.87315144,  1.10632974],
       [-0.33947615, -1.24637147],
       [ 1.3639769 ,  1.10632974],
       [ 1.12337618, -1.24637147],
       [ 1.97029069, -0.07002087]])

### Regression with scaled features

In [33]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [34]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [35]:
reg.intercept_

np.float64(3.330238095238095)

In [46]:
# reg_summary = pd.DataFrame(data = ['Bias', 'SAT', 'Rand 1,2,3'], columns = ['Features'])
reg_summary = pd.DataFrame([['Bias'], ['SAT'], ['Rand 1,2,3']], columns = ['Features'])

reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [47]:
reg_summary

     Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030